# Site settings
title: "Sandeep Kumar"
email: sandeep.k1977@gmail.com
description: "Sandeep's blogs"
baseurl: ""
url: "https://sandeepk1977.github.io/"
title_description: "Developer, agilist, learner and dreamer. Welcome to my little world."
title_image: "images/sandeep.jpg"
google_analytics: "UA-127173510-1"
disqus_account: https-sandeepk1977-github-io
github_repository: https://github.com/sandeepk1977/sandeepk1977.github.io
addthis_id: ra-5bbce3db6ff52e23
post_limit: 5

# Social usernames/URLs
twitter_username: sandskum
github_username:  sandeepk1977
instagram_username: 
reddit_username: 
linkedin_link: https://www.linkedin.com/in/sandeep-kumar-safe-agilist%C2%AE-pmi-acp%C2%AE-csm%C2%AE-pmp%C2%AE-1941ba15/
google_plus_link: https://plus.google.com/+SandeepKumars
stackoverflow_link: https://stackoverflow.com/users/10488369/sandeep-kumar
xing_link:
facebook_link:

# Footer
# footer_left: "Site run and maintained by <a href=\"https://twitter.com/sandskum\">Sandeep Kumar</a>"
footer_left:  "<a href=\"mailto:sandeep.k1977@gmail.com?subject=Feedback about Sandeep's blogsite\">Feedback</a> &nbsp; <i class=\"fa fa-envelope-o\"></i>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/sandeepk1977/sandeepk1977.github.io\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
